#------------------#
#
# System Monitor
#
#------------------#

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: 'C:'
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot
    - type: since_last_boot
