#------------------#
#
# Weather Underground
#
#------------------#

- platform: wunderground
  api_key: !secret wunderground_key
  monitored_conditions:
    - alerts
    - precip_1d
    - pressure_trend
    - temperature_string
    - weather
    - weather_2d
    - weather_3d
    - weather_4d
    - wind_mph
